# Generated by Django 4.0.4 on 2022-05-29 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
