# Generated by Django 4.0.4 on 2022-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0002_shop_shopid_shop_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
